### ISSUE TITLE
Assumes Senzing install path

### ISSUE THREAD

**Issue by jeffadair** [Senzing/docker-python-mysql-base#14]
**Describe the bug**
Hard coded paths assume where senzing is installed.

**To Reproduce**
Install Senzing to somewhere other than /opt/senzing. Run this container

**Expected behavior**
Container should work with Senzing installed anywhere, as long as you tell it where it is.

**Desktop (please complete the following information):**

- OS: CentOS 7

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/docker-python-mysql-base/pull/15
